# Generated by Django 5.1.3 on 2025-06-04 03:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ekstra Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fiyatı')),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('sauce', 'Sos'), ('veggie', 'Sebze'), ('cheese', 'Peynir'), ('other', 'Diğer')], max_length=50, verbose_name='Ekstra Kategorisi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mevcut mu?')),
            ],
            options={
                'verbose_name': 'Menü Ekstrası',
                'verbose_name_plural': 'Menü Ekstraları',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug (URL Dostu Ad)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Kategori Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.category', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Slug (URL Dostu Ad)')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Temel Fiyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_item_images/', verbose_name='Ürün Resmi (16:9 önerilir)')),
                ('preparation_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hazırlık Süresi (dakika)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Ortalama Puan')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Toplam Değerlendirme Sayısı')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mevcut mu? (Stok Durumu)')),
                ('is_chef_recommendation', models.BooleanField(default=False, verbose_name='Şefin Önerisi mi?')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popüler mi?')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vejetaryen mi?')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegan mı?')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Glutensiz mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('available_extras', models.ManyToManyField(blank=True, to='menu.menuextra', verbose_name='Mevcut Ekstralar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Menü Öğesi',
                'verbose_name_plural': 'Menü Öğeleri',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kullanıcı Adı (opsiyonel)')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puan (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Değerlendirme Tarihi')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem', verbose_name='Menü Öğesi')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
